# Generated by Django 4.0.3 on 2022-03-11 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='user_profile')),
                ('pic_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userinfo.userinfo')),
            ],
        ),
    ]
